// This file was autogenerated by `crates gen`. Do not edit!
fn main() {
    let version = rsp2::version::get();
    rsp2_tasks::entry_points::layer_mode_frequencies("rsp2-layer-mode-freqs", version);
}
