// This file was autogenerated by `crates gen`. Do not edit!
extern crate rsp2_tasks;
extern crate rsp2;

fn main() {
    let version = ::rsp2::version::get();
    ::rsp2_tasks::entry_points::rsp2_acgsd_and_dynmat("rsp2-acgsd-and-dynmat", version);
}
