// This file was autogenerated by `crates gen`. Do not edit!
fn main() {
    let version = ::rsp2::version::get();
    ::rsp2_tasks::entry_points::print_library_paths("rsp2-library-paths", version);
}
