// This file was autogenerated by `crates gen`. Do not edit!
fn main() {
    let version = rsp2::version::get();
    rsp2_tasks::entry_points::save_bands_after_the_fact("rsp2-save-bands-after-the-fact", version);
}
