// This file was autogenerated by `crates gen`. Do not edit!
fn main() {
    let version = rsp2::version::get();
    rsp2_tasks::entry_points::compute_for_phonopy("rsp2-compute-for-phonopy", version);
}
