#!/usr/bin/env python3

import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.realpath(__file__)), '..')

with open(os.path.join(ROOT, '../Cargo.toml')) as f:
    if "profile.dev.overrides" in f.read():
        print("""
Please remove nightly features from Cargo.toml:

    ./crates gen --vcs
""".strip(), file=sys.stderr)
        sys.exit(1)
