#!/usr/bin/env bash

RSP2=$(dirname "$(dirname "${BASH_SOURCE[0]}")")
PKGNAME=rsp2-bond-polarizability-bin
BINNAME=rsp2-bond-polarizability
BINPATH=$RSP2/target/release/$BINNAME

cargo run --manifest-path "$RSP2/Cargo.toml" --package="$PKGNAME" --release -- "$@"
