[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
!!LICENSE-PERMISSIVE
!!DEFAULT-EDITION

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-array-types
!!rsp2-structure
!!rsp2-util-macros

!!enum-map
!!thiserror
!!log
!!serde { optional = true, features = ["derive"] }
!!serde-json { optional = true }

[features]
!!NIGHTLY-FEATURE-LINE

# Once namespaced-features are stabilized, these features will be renamed after the deps.
# see https://github.com/rust-lang/cargo/issues/1286 (problem and proposal)
#     https://github.com/rust-lang/cargo/issues/5565 (tracking issue, of sorts)
serde-support = ["serde", "serde_json"]
